lib/commands/release.js

We're getting closer! Fixes:
```
TypeError: Cannot set property 'pr' of undefined
at verify (/home/travis/build/groupon/nlm/lib/commands/verify.js:66:14)
at release (/home/travis/build/groupon/nlm/lib/commands/release.js:97:10)
at Object.<anonymous> (/home/travis/build/groupon/nlm/lib/cli.js:98:3)
```

Pass arguments to verify command

---

lib/commands/release.js

`.then(publishToNpm)` wasn't passing the required `(cwd, pkg, options)` arguments. Running it as a task like all the others fixes that.

fix: Call publishToNpm as a task/step

---

lib/steps/publish-to-npm.js
test/steps/publish-to-npm.js

If a package has `private: true` set, we can do Github releases etc. but we shouldn't try to publish it to npm.

Never publish private packages

---

README.md
lib/commands/verify.js
lib/steps/release-info.js
test/steps/release-info.test.js

Sometimes a project might pull in 3rd-party commits where rewording would not be acceptable, e.g. since it would complicate future merges. This isn't a great solution but it offers a stop-gap measure.

Opt-in `acceptInvalidCommits` option

---

lib/github/parse-repository.js
lib/steps/changelog.js
test/steps/changelog.test.js

Fixes https://github.com/groupon/nlm/issues/14

Handle missing and foreign PRs in changelog

---

lib/git/commits.js
lib/steps/changelog.js
lib/steps/pending-changes.js
test/fixtures/ticket-commits
test/git/commits.test.js
test/steps/changelog.test.js
test/steps/pending-changes.test.js

Most of the changes are additional tests. The short version is that `nlm` now accepts any url that ends with a number (more or less) as an acceptable argument to `Closes <x>`. There's special logic for both Jira-style and Github-style URLs to make them a bit prettier. This includes the "smart collapsing" Github itself does when a full URL is mentioned but it points to an issue in the current repository.

Link to issues and tickets in changelog

---

.travis.yml

This prevents successful releases from CI.

Fix typo in travis config

---

lib/commands/release.js

If `npm publish` fails, you're left with a version that nlm believes is
real (has tag, CHANGELOG, GH Release, etc.), but that doesn't exist on
the npm registry.  Restarting the CI job doesn't help, because you
either get an attempted dup commit, or the changes are "none" so it
aborts.
This change makes it so that when you re-run a CI job for a version
bump/CHANGELOG commit, it will double-check that the current version
is published, and try (again) to publish it if it's not.

feat: re-check publish status for releaseType none

---

lib/license/index.js

Previously a project that didn't have a LICENSE would have its entire workspace crawled before the result was dismissed.

Only scan for files if LICENSE is present

---

lib/commands/verify.js
test/commands/verify.test.js
test/fixtures/non-git

This allows running `npm test` in projects using `nlm` even when the code was checked out by other means (e.g. downloaded the source tarball from github).

Skip verify in non-git directories

---

lib/steps/changelog.js
test/steps/changelog.test.js

It's easier to get teams to adopt `nlm` (and eventually good git practices) if it provides some value even before they change their ways. Fixes #16. (Seems I forgot to push this to github. :-)

acceptInvalidCommits formatter

---

package-lock.json

This PR only exists to work around a travis bug where rebuilding a branch that points to a tag causes a *tag* build instead of the actual branch build.

Keep package-lock in sync

---

lib/steps/version-commit.js
test/fixtures/with-bogus-plock
test/fixtures/with-plock
test/steps/version-commit.test.js

iff you have an in-use `package-lock.json` (not in `.gitignore`),
as part of the version bump commit, we'll go ahead and bump the version
here too - that way you don't get a diff later on when you do an `npm i`

update version field in package-lock.json

---

CONTRIBUTING.md

- Looks like angular may have moved their documentation around a little, had to search to find their references to commit format.
- This PR updates the link to point directly to the `Commit Message Format` doc.

docs: Update angular link to point directly to commit guidelines

---

lib/commands/changelog.js
lib/commands/release.js
lib/commands/verify.js

Unlike real async/await, the yields you use with co.wrap explode if you
don't hand them a real Promise.  Let's just wrap the risky ones at their
point-of-use to make it easy to strip them back off when we port to real
async/await in the future.

wrap risky co.wrap yields

---

README.md
lib/commands/release.js
lib/steps/execute-prepare-hook-command.js
test/steps/execute-prepare-hook-command.test.js

This PR adds support for hooks in `nlm release` command. So far only one hook has been implemented but the design allows to add more hooks in the future without breaking changes. 
The hook implemented is the `prepare` hook, which is called between version bump and commit steps and is capable of executing any given shell command. This command should be defined in the an `nlm` section in `package.json`, like this: 
```javascript
"nlm": {
"hooks": {
"prepare": "<add_your_command_here>"
}
}
```
As part of the command execution `nlm` will provide the value of the **nextVersion** as an environment variable **NLM_NEXT_VERSION**.

feat: add support for hooks in release command

---

README.md
lib/commands/verify.js
lib/steps/detect-branch.js

Adding support for CircleCI.
* circleci uses the `CIRCLE_PULL_REQUEST` env var to designate the pull request URL (I pull the id from it in the code)
* circleci uses the `CIRCLE_BRANCH` env var to designate the branch
* added some description in the `READEME` on how to setup auto releasing from master builds
Testing `nlm` with circleci here in this PR: https://github.com/Automattic/vip-search-replace/pull/1
And am currently not getting auto labelling of semver updates on the PR without these changes.
Please feel free to add a `hacktoberfest-accepted` label to the PR if you feel it's worthy 👍  🤓 🙇‍♂️

feat: support circleci PRs and releases

---

README.md
lib/steps/changelog.js
test/steps/changelog.test.js

Will now be able to categorise PRs containing scopes like `fix(changelog): something`

fix(changelog): type(scope) detection

---

README.md
lib/cli.js

Adds support for the `main` branch in the channel list by default, in line with ELIT initiatives across other Groupon repositories.
Also updates the README file to reflect the change.

feat: support main branch for release

---

lib/cli.js
lib/github/client.js
package-lock.json
package.json

follow up to https://github.com/groupon/nlm/pull/57#discussion_r374845762

refactor: client syntax to match modern Gofer

---

.github/workflows/npm-publish.yml
README.md

🤦  copy & paste
https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

ci(actions): fix publish to default branch

---

lib/steps/version-commit.js
package-lock.json
test/fixtures/with-plock1
test/steps/version-commit.test.js

We were handling the version entry at the top of v1 lockfiles, but as of npm 7
there's an extra entry so we'll bump the version on that too
* chore: upgrade to lockfile v2
* feat: support v2 lockfile version bumping
* chore: npm audit fix
---
_This PR was started by: [git wf pr](https://github.com/groupon/git-workflow/releases/tag/v1.3.4)_

package-lock.json v2 version bumping

---

.github/workflows/npm-publish.yml
lib/git/commits.js
lib/steps/pending-changes.js
package.json
test/fixtures/multiple-commits
test/git/commits.test.js

The intention of #90 was to limit the scope of change calculations to
only those on the local branch.  This is problematic for a number of
reasons:
1. It actually makes publishing in the standard CI flow impossible - the
nlm job runs after the PR has already been merged to main, making the
list of commits zero.  The only reason this release published
successfully is that this repo was set to use the prior version of
`nlm`, thus evading this bug (fixed in additional commit on this PR)
2. It results in inaccurate version bump selection/CHANGELOG entries:
the release will include **everything** on `main`, not just the
commits in the current branch, so we shouldn't publish a false
record of activity.
---
_This PR was started by: [git wf …

Undo commit listing changes from #90
